branch-defaults:
  master:
    environment: cjphotosflapp
    group_suffix: null
environment-defaults:
  Cjphotosflapp-env:
    branch: null
    repository: null
global:
  application_name: cjphotosflapp
  branch: null
  default_ec2_keyname: cjphotoskey
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.7.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
